### ISSUE TITLE
High fidelity design & mockups

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/swanningaround#16]
Please create a high fidelity mockup of the new swanning around site as define by the epic #13 and all supporting page wireframes.  The mockup should

* provide designs for both webUI and mobile experience
* be implemented as a clickable experience on invision app - project  https://projects.invisionapp.com/d/main#/projects/prototypes/19077968

**Comment by fritzelemino** [comment]
Hi @onthebreeze , please check this:

https://invis.io/HTVAL2AJNV5#/398087365_Swanning-Around

**Comment by onthebreeze** [comment]
Logo, Favicon & Fonts

[LOGO PSD.zip](https://github.com/gs-gs/swanningaround/files/3991910/LOGO.PSD.zip)
[FONT.zip](https://github.com/gs-gs/swanningaround/files/3991911/FONT.zip)
[FAVICON.zip](https://github.com/gs-gs/swanningaround/files/3991912/FAVICON.zip)

**Comment by onthebreeze** [comment]
Mobile design: https://projects.invisionapp.com/share/GPVB7QQCZNH#/screens/398645987_Swanning-Around-Mobile

Web design: https://projects.invisionapp.com/share/HTVAL2AJNV5#/screens/398087365_Swanning-Around

**Comment by fritzelemino** [comment]
Hi @onthebreeze @webilhan , 

Please check PSDs here:
https://www.dropbox.com/sh/xz3hxemusdvxhnt/AAB1osHo8PKahRlNn4-x4BaBa?dl=0

Thank you.

**Comment by onthebreeze** [comment]
Hi fritz.  some feedback

The discovery page should show all ocean passage/race experiences as polylines and all cruise/regatta experiences as polygons with a central pin.  Currently you only show the line when someone clicks on a pin - that is wrong.  A line represents an experience and a pin polygon/pin represents another experience.  You show all lines and pins that match the filter conditions (date range & experience type)

**Comment by onthebreeze** [comment]
on the discovery view we should annotate both the lines and the pins with the experience "title" - for example "Sydney to Auckland" might be a title for a passage (ie a line) and "Tahiti Pearl Regatta" might be a title for a pin.

**Comment by onthebreeze** [comment]
one thing that may be a bit confusing is the scale difference between the ocean race/passage experiences and the cruise/regatta experiences.

* the passages will usually be at least 1000 miles long, sometimes much longer.  so they are shown as a google maps  polyline
* cruises and regattas are confined to a local area, such as around tahiti -  rare to go much more than 50 or 100 miles in a cruise, even less in a regatta.  So they are shown as polygons with a pin in the middle.

When you are zoomed out to the level of the whole australia/south pacific region then it is maybe 5000 miles across the map - so the little polygons representing (for example) the cruise around tahiti will be hardly visible - but the pin will be the same size no matter the scale of the map.  That's why we need a pin for the cruise/regatta experiences.

but then a user is looking only at one cruise /regatta experience (either because they have clicked on the "read more.." about that experience - or because they chose filters on the discovery page that match only one location - then the map will zoom in a lot and the polygon will become visible.

**Comment by onthebreeze** [comment]
also, if you read https://github.com/gs-gs/swanningaround/issues/18 carefully, you'll see that I am suggesting a different coloured polyline for race vs passage and a different coloured polygon & pin for a cruise vs a regatta

**Comment by fritzelemino** [comment]
Hi @onthebreeze , 

Kindly check if this works:
https://invis.io/7YVE46KV8KB#/398087363_SA-Discovery-Page-Hide-Details

Let me know your thoughts
