### ISSUE TITLE
initial content for experience pages

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/swanningaround#21]
This ticket is a placeholder for the initial content for several experience pages - all will match the templates defined in #17 (noting that meta data is slightly different for each experience type as indicated in #18 

Content pages - with correct coordinates & dates & prices - are needed for:

* Sydney-Auckland passage
* Auckland-Gambier passage
* Gambier-Tahiti passage
* Tahiti Pearl regatta
* Cruising Tahiti
* Cruising Marquesas

and what else?

Ilya will load this content to github/cloud canon with nice arrangement & formatting - so that future pages are easy for ben & jess to copy directly from other pages on cloud canon.

refs #13

**Comment by benjaminroulant** [comment]
Hi, 

For the journey from Sydney to Tahiti, divided in 4 legs, you'll get a 'summary'doc and a 'read more' doc per leg. 

[READ MORE LEG1 : Sydney AUS : Bay of Island NZ copy 2.pdf](https://github.com/gs-gs/swanningaround/files/3976176/READ.MORE.LEG1.Sydney.AUS.Bay.of.Island.NZ.copy.2.pdf)
[SUMMARY LEG1 : Sydney AUS : Bay of Island NZ.pdf](https://github.com/gs-gs/swanningaround/files/3976177/SUMMARY.LEG1.Sydney.AUS.Bay.of.Island.NZ.pdf)

**Comment by benjaminroulant** [comment]
[READ MORE LEG2 : Bay of Island : Iles Gambier PYF .pdf](https://github.com/gs-gs/swanningaround/files/3976196/READ.MORE.LEG2.Bay.of.Island.Iles.Gambier.PYF.pdf)
[SUMMARY LEG2 : Bay of Island : Iles Gambier PYF .pdf](https://github.com/gs-gs/swanningaround/files/3976197/SUMMARY.LEG2.Bay.of.Island.Iles.Gambier.PYF.pdf)

**Comment by benjaminroulant** [comment]
[READ MORE LEG3&4 :  Iles Gambier PYF : TAHITI VIA ILES AUSTRAL ISLANDS.pdf](https://github.com/gs-gs/swanningaround/files/3976208/READ.MORE.LEG3.4.Iles.Gambier.PYF.TAHITI.VIA.ILES.AUSTRAL.ISLANDS.pdf)
[SUMMARY LEG3&4 :  Iles Gambier PYF : TAHITI VIA ILES AUSTRAL ISLANDS.pdf](https://github.com/gs-gs/swanningaround/files/3976209/SUMMARY.LEG3.4.Iles.Gambier.PYF.TAHITI.VIA.ILES.AUSTRAL.ISLANDS.pdf)

**Comment by onthebreeze** [comment]
Good stuff.  

Note that google maps API uses simple signed decimal for coordinates - so 

* not NSEW qualified deg.min like "33o49.623’S / 151o17.007’E
* but simple signed decimal lat:-33.83, lng:151.28

please use the signed decimal representation or ilya will have trouble tranposing

also - we cannot extract images from pdf so no use sending pdfs like this.  instead, I suggest you create an instagram post, load the photo(s) and then provide the post URL.

**Comment by onthebreeze** [comment]
[EVE - Sydney_Tahiti METADATA Leg 1 to 4.xlsx](https://github.com/gs-gs/swanningaround/files/3976711/EVE.-.Sydney_Tahiti.METADATA.Leg.1.to.4.xlsx)

Here's the structured data for the first few experience pages  - they are all passages.  Next we'll get data for tahiti pearl regatta, tahiti cruising, and marquesas cruising..

**Comment by onthebreeze** [comment]
and here is metadata for some cruise experiences

[CRUISE METEDATA.xlsx](https://github.com/gs-gs/swanningaround/files/3977379/CRUISE.METEDATA.xlsx)

**Comment by onthebreeze** [comment]
and here is the metadata for one regatta

[EVE - Regatta METADATA .xlsx](https://github.com/gs-gs/swanningaround/files/3977380/EVE.-.Regatta.METADATA.xlsx)
