### ISSUE TITLE
Map explorer doesn't work in Safari

### ISSUE THREAD

**Issue by benjaminroulant** [gs-gs/swanningaround#24]
Hi, I'm using a MacBook Air with safari and when opening this page https://smooth-falcon.cloudvent.net/explore, the map doesn't show, while it shows when using google chrome.

**Comment by webilhan** [comment]
@benjaminroulant @onthebreeze Issue in Safar fixed. Please check.

**Comment by benjaminroulant** [comment]
Nice work it works perfectly
