### ISSUE TITLE
Static page crew 

### ISSUE THREAD

**Issue by benjaminroulant** [gs-gs/swanningaround#26]
Hi, Could you display the crew static page as comes on the attached excel file ?
Thanks
[The Crew.xlsx](https://github.com/gs-gs/swanningaround/files/4070904/The.Crew.xlsx)

**Comment by onthebreeze** [comment]
I think we need a special design for crew pages - especially if we want to add customers as crew.  That'll take a bit of time so, for now just put name, photo, and personal story as txt - no Q&A table as it won't render well on mobile

**Comment by webilhan** [comment]
@onthebreeze @benjaminroulant I've added crew as collections, so each member could be edited separately. Applied base layout design, see: https://smooth-falcon.cloudvent.net/crew.html
This could be used as start for design. We also could create crew member detail page with custom design for each member, for now I've disabled this feature.

**Comment by JessiJess** [comment]
@webilhan thank you! It is perfect.
@onthebreeze, would you please update your section with picture and description?
