### ISSUE TITLE
home page graphic & video

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/swanningaround#27]
Lets remove the "watch video" link on the home page and instead just have a static image that lazy-loads to become a video that plays in a loop.

website should not wait for complete video load before allowing user to "explore our world" or select a hamburger option.  It should load only the first frame static image.  But if the user stays on the home page, the video should load and play in the background

we will update the video from time to time but we can start with this one https://drive.google.com/open?id=1WrWxzHrpysmNJ0DYj74OsMnWrUcTkQSc

**Comment by webilhan** [comment]
@onthebreeze Updated homepage with new video. Please check.

**Comment by onthebreeze** [comment]
done ok
