### ISSUE TITLE
map is not centred on experience detail view

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/swanningaround#29]
after clicking on "read more" on an experience summary in explorer view, the user is taken to the experience detail view.  The map should display correctly showing the experience in the centre of the map.  But is does not.  See screen shots

![experiencedetail-map issue](https://user-images.githubusercontent.com/13426392/72776330-ec2da800-3c65-11ea-882a-c6cd1772234b.png)
![explore-selectexperience](https://user-images.githubusercontent.com/13426392/72776331-ecc63e80-3c65-11ea-957d-94e04fa190d0.png)

**Comment by webilhan** [comment]
@onthebreeze Added fix. Please check if bug still happens

**Comment by onthebreeze** [comment]
good - it's working fine now.
