### ISSUE TITLE
Add a calendar view of experiences

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/swanningaround#30]
It would be nice to be able to toggle between the map explorer ("where do I want to go?") and a calendar view of the same data ("when do I want to go?").

Suggest that we add an action button next to the filters that says 

* "switch to calendar view" when in map view
* "switch to map view" when in calendar view

And we create a calendar view of the same experience data something like this. The user needs to be able to quickly scroll up and down some kind of date slider control to see a n ordered list of experiences.  when the user clicks on one then he/she sees exactly the same summary panel as if he/she clicked on an experience (line or area) on the map view.  It's just a different way to explore the same data.

![swanningaround-calendar](https://user-images.githubusercontent.com/13426392/72784578-3d956180-3c7d-11ea-8b1a-9c0140e486fe.png)

And we add that toggle button something like this

![Swanning Around - explorer with calendar button](https://user-images.githubusercontent.com/13426392/72784724-8ea55580-3c7d-11ea-9d33-83a4479a6e62.png)

@fritzelemino to make a design first - then assign this ticket to @webilhan to implement.

**Comment by onthebreeze** [comment]
oh, and dont forget to add a "calendar" item to the hamburger menu for this

**Comment by onthebreeze** [comment]
Ive just realised that there could be situations where some experiences overlap in time.  for example 

* 01 may till 01 Sept in Tahiti & surrounds.
* 01 july till 01 aug in marquesas.

in other words - we are spending a heap of time in tahiti but in the middle we do a one month excursion to marquesas

we should probably show that as overlapping boxes?

**Comment by fritzelemino** [comment]
Hi @onthebreeze , 

Please check this one:
https://invis.io/TVVNHUS7HJ5#/401727241_Calendar-View

I don't think we need to introduce overlapping boxes as long as the starting dates are in order should be understandable already. 

Let me know your thoughts

Regards,

**Comment by fritzelemino** [comment]
@onthebreeze , 

I'm not sure we need to put the calendar view in the main menu. 

If we are to put it where do you want to see it? Should this be under the program?
[![Screenshot from Gyazo](https://gyazo.com/9a0e0f3d657510c9f094aa6bd8d9aa0f/raw)](https://gyazo.com/9a0e0f3d657510c9f094aa6bd8d9aa0f)

**Comment by onthebreeze** [comment]
nice concept.  Issues are

* the calendar view is just an alternative representation of the map view so it will show all experience types. So, for the hamburger lets just leave "Explore" as the option (which is current state) and let the user pick map/calendar as you show.
* Because the calendar view shows all experience types, we need a way to distinguish between "Passage", "Race", "Regatta", and "Cruise".  so probably a label on each calendar panel.
* many experiences cross over the month and some last several months so a specific month will often have only one experience.  So picking a month and showing only experiences for that month is not really giving an "explore" big picture view of timing.  I think we need to show experiences as a time series (so you always fill the screen with panels) and the date selector is maybe some kind of slider / scroll and the display just shows a list of experiences centered on the selected month.  so, for example, if i slide the date to July 2020, i will see stuff from may 2020 till september 2020.
* this means that the experience panel is not just day range (eg 11-17) but should include month (eg may 11 - jun 14).

**Comment by fritzelemino** [comment]
Hi @onthebreeze , 

I updated invision app, kindly check this one:
https://invis.io/TVVNHUS7HJ5#/401727241_Calendar-View

For date slider, does this mean we won't allow users to pick specific dates? They can only select months with year?

Let me know your thoughts

**Comment by onthebreeze** [comment]
Hi fritz,

Yes that is getting better, thank you.  

Regarding date slider, I dont see much value in picking particular days because most experiences are weeks or months.  so a quick way to select from/to period as month/year would be good.  your thoughts welcome.

**Comment by onthebreeze** [comment]
lets just implement the calendar view as start-date ordered list of panels (earliest date at the top) - and we show as many panels as match the filter criteria.  

so just load the PSD

**Comment by fritzelemino** [comment]
Hi @webilhan ,

Please check PSD here: https://www.dropbox.com/s/bxsuglz1c2m8zgj/Calendar-view-v2.psd?dl=0

Thank you.

**Comment by webilhan** [comment]
Deployed to Prod

**Comment by onthebreeze** [comment]
Test ok - thanks
