### ISSUE TITLE
user tip is obscured after clicking on an experience

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/swanningaround#31]
the screen shots are self-explanatory

![move screen tip](https://user-images.githubusercontent.com/13426392/72785174-b648ed80-3c7e-11ea-94d9-4b84b1defbc7.png)

![move screen tip target](https://user-images.githubusercontent.com/13426392/72785191-c06aec00-3c7e-11ea-84f4-5beb7d115555.png)

**Comment by webilhan** [comment]
@onthebreeze Move user tip to the top right corner.

**Comment by onthebreeze** [comment]
good - fixed
