### ISSUE TITLE
Add an "Eve Tracker" page

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/swanningaround#32]
Lets try adding a new option to the hamburger menu which is an "Eve Tracker" that embeds the predict wind tracker iframe as per 

Please see the Codepen example at http://codepen.io/anon/pen/BoPbXp with a few options of how you can add the iframe.You can use a simple iframe embed, the styled one (no border and specific  sizes), or a responsive one, that will scale up and down for mobile/desktop

Eve link is http://forecast.predictwind.com/tracking/display/EVE

try this in dev system first please

**Comment by webilhan** [comment]
@onthebreeze Added Eve Tracker page with embedded iframe on DEV site. Please check - https://smooth-falcon.cloudvent.net/eve-tracker

**Comment by onthebreeze** [comment]
nice - lets merge it to production

**Comment by webilhan** [comment]
Merged to Production.

**Comment by onthebreeze** [comment]
nice - all good.
