### ISSUE TITLE
link to general info about experience type - on each experience page

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/swanningaround#33]
We have four static pages that describe each experience type

* ocean passages
* Regattas
* Cruising
* Ocean races

We should add a link to the relevant experience type static page on each experience summary panel and detail view.  so if i'm looking at a cruising experience then the link will take me to the cruising static page.  something like this.

![Swanning Around - about experience type](https://user-images.githubusercontent.com/13426392/72786476-cdd5a580-3c81-11ea-8f39-ebc4c8320b9f.png)

and this 

![experience detail - about experience type](https://user-images.githubusercontent.com/13426392/72786506-dcbc5800-3c81-11ea-8bcc-41c58604b2d3.png)

@fritzelemino may care to offer some design advice on this.

**Comment by fritzelemino** [comment]
Hi @onthebreeze and @webilhan , 

Here's how I suggest we do it, please check:
https://invis.io/GWVNWMI3TP9#/398785563_Passage-Details
https://invis.io/SWVNWN9HBUV#/398087364_SA-Discovery-Page

When they hover this text, there should be an underline to it so people know this is clickable. 

Also, I notice on Experience details page, most of the experiences have multiple pricing. On the live site, it's currently missy, I suggest we stick with one price at the top with one big "Enquiry button" just like my original design [![Screenshot from Gyazo](https://gyazo.com/1c92a983d3762338ac25fe8b30d53174/raw)](https://gyazo.com/1c92a983d3762338ac25fe8b30d53174)

But now, if there's more than one price we add a text (see pricing) that will bring them down to the bottom of the page. The "Pricing Details" section: https://invis.io/GWVNWMI3TP9#/398785563_Passage-Details

Is it necessary to have Enquiry button for each of the price? If not, I suggest to remove it. 

Let me know your thoughts

**Comment by webilhan** [comment]
@fritzelemino I think it is not obvious that "Ocean Passage" above the title is link, maybe we should highlight is somehow?

**Comment by onthebreeze** [comment]
the main purpose of this ticket is to add that link to the relevant experience type static page (eg to something like [About regatta experiences](https://swanningaround.com/regattas.html) on every regatta experience page

how we organise pricing is a different question.  Problem is we cant pick one of the prices for the slpach image because there's a big difference between the per person price and the whole boat price.  which one to show?

**Comment by webilhan** [comment]
@onthebreeze Added links to explore and experience detail page.

**Comment by onthebreeze** [comment]
ok good stuff
