### ISSUE TITLE
contact us updates & fixes

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/swanningaround#36]
please see screenshots.

Contact us page

* the map is not needed - nobody will visit the head office and now that we have the eve tracker page we dont need a map here.  just put a nice background photo - for now the same as the home page.
* add a title to the info box "swanning around head office"
* add tip to user to include country code in phone number

Thanks for your message page

* the button text is not readable.  

![Contact Us UI changes](https://user-images.githubusercontent.com/13426392/72871648-8f062500-3d3f-11ea-9ca1-777abdd4549f.png)
![MessageSentUI](https://user-images.githubusercontent.com/13426392/72871649-8f062500-3d3f-11ea-9696-6c9557421b7d.png)

**Comment by webilhan** [comment]
Done. Deployed to Test site for testing - https://smooth-falcon.cloudvent.net/contact-us.html
@onthebreeze Please check

**Comment by onthebreeze** [comment]
looks fine - please deploy to prod

**Comment by webilhan** [comment]
Deployed to Prod.

**Comment by onthebreeze** [comment]
ok good - tested ok
