### ISSUE TITLE
Sex up the static pages - they are a bit boring

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/swanningaround#37]
take a look at : https://swanningaround.com/regattas.html

it's a boring layout.  Each static page will always have

* a main heading and one level of sub-heading (but multiple H2 subheadings)
* multiple photos
* one video
* a number of attached docs (eg pdfs)
* various bits of text with bulleted/numbered lists.

what can we do to sex up this static page layout?

**Comment by onthebreeze** [comment]
except crew page - which is a bit special. We will also add some free text and some attachments (pdf) of things like professional certifcates to each crew profile.

**Comment by fritzelemino** [comment]
Hi @onthebreeze , 

Kindly check this one: https://invis.io/KMVP85JA35P

I recommend we create a mock up for all of these subpages and give it to ilya to give him guidance. As right now, these are too generic, we can spice this up to match other pages.

Thank you

**Comment by onthebreeze** [comment]
Yes that is good.  I think we can use that same template for each of the four experience type pages.  The only thing we need to add is a place to highlight the legal terms and conditions for the experience type.  I will add that to the current boring pages this morning 

Please release psd for Ilya 

I’ll update the other static pages with more content and then you can take a look and redesign

**Comment by fritzelemino** [comment]
Kindly check the PSD here:

@webilhan https://www.dropbox.com/s/pc8axjbn5hh314u/the-programs-Regattas.psd?dl=0

**Comment by fritzelemino** [comment]
@onthebreeze , 

Let me know when we are ready to take a look at the subpages again

**I’ll update the other static pages with more content and then you can take a look and redesign**

Thank you

**Comment by onthebreeze** [comment]
good to go - please deploy to production.

**Comment by webilhan** [comment]
Deployed to production

**Comment by onthebreeze** [comment]
tested all good - closing this ticket
