### ISSUE TITLE
urgent contact us bug

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/swanningaround#38]
validation is toot restrictive on the name field - it wont allow spaces.  

should probably allow all printable characters.

see screenshots 

![Contact Us - Swanning Around - space error](https://user-images.githubusercontent.com/13426392/73116708-f36af380-3f8e-11ea-9d0e-caecc43e1165.png)
![Contact Us - Swanning Around - no space](https://user-images.githubusercontent.com/13426392/73116709-f4038a00-3f8e-11ea-886b-e03f2ec94b0f.png)

**Comment by webilhan** [comment]
Fixed

**Comment by onthebreeze** [comment]
checked ok
