### ISSUE TITLE
Refactor hamburger to remove "program" and elevate sub-pages

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/swanningaround#39]
Feedback from early users is that it is too hard to find the sub-pages under "The Program".  Also the current content on the program page is fairly light and really just provides a link to the lower level pages anyway.

so - lets

* elevate the four sub-menu items to top level menu items and position them just below the "Explore" item.  
* get rid of "The program" menu item and the related page.

**Comment by webilhan** [comment]
Done

**Comment by onthebreeze** [comment]
tested ok
