### ISSUE TITLE
Add "stay informed" link - via mailchimp sign-up form

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/swanningaround#41]
Add an email list sign-up link to the top left of all pages (next to the facebook & instagram links.  clicking on an email icon will open the mailchimp subscription form using the signup link below

Signup link:

```
http://eepurl.com/gQYAcn
```

![newsletter link - Swanning Around](https://user-images.githubusercontent.com/13426392/74079565-3d72cf80-4a8d-11ea-940e-e6e59cf02a5e.png)

Also - lets investigate feasibility of triggering a pop-up similar to https://www.pilgrimsailing.com.au/ after a period of time on the website.  If a user has spent 30 seconds on the site then pop-up the sign up form.  Allow user to decline or provide details & signup.  Dont popup the form again if the user has closed/declined in the session.  also, write a cookie of they have signed up and then never show it again (in any session) for users that have the cookie.

```
<!-- Begin Mailchimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://swanningaround.us17.list-manage.com/subscribe/post?u=adbd467bca9ba2054231a1998&amp;id=08bfcf2a97" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Subscribe</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">First Name </label>
	<input type="text" value="" name="FNAME" class="" id="mce-FNAME">
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Last Name </label>
	<input type="text" value="" name="LNAME" class="" id="mce-LNAME">
</div>
<div class="mc-field-group">
	<label for="mce-MMERGE6">Your interests </label>
	<input type="text" value="" name="MMERGE6" class="" id="mce-MMERGE6">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_adbd467bca9ba2054231a1998_08bfcf2a97" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[6]='MMERGE6';ftypes[6]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
<!--End mc_embed_signup-->
```

**Comment by onthebreeze** [comment]
<img width="1680" alt="Screen Shot 2020-02-17 at 9 41 07 pm" src="https://user-images.githubusercontent.com/13426392/74646612-4fabe680-51ce-11ea-9067-bc52f30c6a04.png">

**Comment by webilhan** [comment]
@onthebreeze Do you think we need to create separate cookies for users who just close the popup and for users who subscribed?

**Comment by onthebreeze** [comment]
yes that would probably make sense.

* closed => dont pop-up again for 24 hours
* subscribed => dont pop up again

maybe we should also put an "iv'e already subscribed" button - for those that subscribed on on their phone and now look at the site again on their browser.  cookie action is the same as subscribed => dont pop up again..

**Comment by webilhan** [comment]
Add subscribed form popup. Please check on DEV how it looks and if subscription works correctly because I don't have access to MailChimp.
https://smooth-falcon.cloudvent.net/
For now, it shows popup after 30seconds.
Here is available settings: http://prntscr.com/r49wg0

**Comment by onthebreeze** [comment]
probably separate cookies is a good idea yes.  because then we can always timeout the ones that just close the window.

**Comment by onthebreeze** [comment]
It's good - lets release it to prod.

**Comment by onthebreeze** [comment]
although maybe it would be nicer if the little email subscription link top right had the same look and feel as the pop-up.  So when user clicks they get the same popup and not the context switch to the mailchimp registration page..
