### ISSUE TITLE
tracking bookings and availability

### ISSUE THREAD

**Issue by onthebreeze** [gs-gs/swanningaround#42]
We need to update the experience meta-data in order to manage capacity and bookings.  This is so that we can show which opportunities are booked and what is still available.

For passages, races, and regattas, we are selling per person.  So we need to add:

```
{
.. other data ..
    "capacity":5,
    "bookings":[{
             "name":"john smith",
             "email":"john@gmail.com"},
                     {
             "name":"ben roulant",
             "email":"ben@hotmail.com"}],
 }
```

in this example, we can see that there are 5 spaces and that two are taken, so there are three left. to anonymous users we only show that there are 5 spaces and 3 remaining - we dont show names & emails of actual bookings.

For cruises, the booking is for the whole boat but for a number of days.  so the availability indicator is by date range.  We need to add structured data as follows:

```
{
.. other data ..
    "bookings":[{
             "name":"john smith",
             "email":"john@gmail.com",
             "fromdate":"21-02-2020",
             "todate":"28-02-2020"},
                     {
             "name":"ben roulant",
             "email":"ben@hotmail.com"
             "fromdate":"02-03-2020",
             "todate":"28-02-2020"}]
             
 }
```

The cruise experience metadata already has a from-to date for the availability of the cruise.  So,if, for example the experience date range for the example above was from 01-01-2020 till 30-03-2020 then the UI would show that the two weeks in february are booked but the remaining time is available. as for the per-person experiences, the names & emails of the customer are provate data, not shown on the public UI.

@fritzelemino  - could you please provide suggestions for how to show these availability indicators on the UI.  

@webilhan - once fritz has shown a workable design then we need to implememnt:

* editing of all data in the cloud canon UI
* display of booked/available places/dates in the UI

**Comment by onthebreeze** [comment]
put detailed booked / available information (including specific dates for cruises) on the details page like this one https://swanningaround.com/cruises/iconic-tahiti.html

Put summary availability info on the calendar panels - something like this

![calendar panel availability](https://user-images.githubusercontent.com/13426392/74653088-95bb7700-51db-11ea-88ec-334f047e0dfa.png)

the same summary data can go on the left hand panel of of explorer - something like this

![Swanning Around - summary panel availability](https://user-images.githubusercontent.com/13426392/74653240-e337e400-51db-11ea-98c9-881e60f46c91.png)

**Comment by fritzelemino** [comment]
Hi @onthebreeze @webilhan, 

Please check these screens:
https://invis.io/7HW0SFRSAPE

The calendar dropdown is both the normal view and the selected view. 

Let me know your thoughts. 

Thank you

**Comment by onthebreeze** [comment]
looks good fritz

but we also need a design for the experience detail page - such as https://swanningaround.com/cruises/iconic-tahiti.html

**Comment by fritzelemino** [comment]
Hi @onthebreeze , 

We have that here: https://invis.io/W5W147RDQBU

Please check

**Comment by onthebreeze** [comment]
yes ok - but that works for passages where we sell per person

We also need to show booked and available dates for cruise experience types

**Comment by fritzelemino** [comment]
Hi @onthebreeze ,

What do you think about putting a calendar view on the page?

https://invis.io/TDW14TRR647

Let em know what you think.

**Comment by fritzelemino** [comment]
Hi @onthebreeze and @webilhan, 

Please check this one:
https://invis.io/C2W1VPNNSQX

Let me know your thoughts

**Comment by JessiJess** [comment]
Hi @fritzelemino,

With regards to the availability in the cruising section, the calendar view (similar to airbnb) is more user friendly, more visual and simple. Can you integrate something like that: 
![image (1)](https://user-images.githubusercontent.com/59960460/74977548-02a26b80-547f-11ea-8810-216bbfa7610e.png)

**Comment by fritzelemino** [comment]
Hi @JessiJess 

Kindly check this one and let me know your thoughts:
https://invis.io/TDW14TRR647

Regards,

**Comment by JessiJess** [comment]
Hi @fritzelemino , yes I am happy with this display. 
Thanks,

**Comment by JessiJess** [comment]
Hi @fritzelemino , I supposed that this issue has been resolved now?

**Comment by onthebreeze** [comment]
a simple system has been implemented, yes. Do you see how to manage calendar in cloud canon?
