### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by JessiJess** [gs-gs/swanningaround#43]
Hi, I have uploaded the video on the home page that was provided by Camille as the quality and colours were definitely better. The last bit that we need to do is to move the logo up and the wording down. Please ref to the attached image (also from Cam).
![image_d___ios_720](https://user-images.githubusercontent.com/59960460/74882829-e8f01e00-53c3-11ea-9e78-851c55c5e68e.jpg)

**Comment by webilhan** [comment]
@JessiJess Updated layout. Please check

**Comment by JessiJess** [comment]
@webilhan perfect thanks.
