### ISSUE TITLE
Static Page - 'About the cruising'

### ISSUE THREAD

**Issue by JessiJess** [gs-gs/swanningaround#44]
Hi @fritzelemino , hope this message finds you well. I am currently reviewing the static pages that were recently re-designed, and I would like to ask you if you could modify slightly the design of 'about cruising' page to have something more consistent with the other static pages. I have made a drawing to give you the idea. Please let me know if this is something that you can do. 
![86721938_194290681815783_3202346483688931328_n](https://user-images.githubusercontent.com/59960460/74883662-9283df00-53c5-11ea-9519-b039b6c15c96.jpg)

**Comment by fritzelemino** [comment]
Hi @JessiJess , 

Just wanted to confirm this is the page you want me to redesign? https://swanningaround.com/cruising.html

I reviewed the page but it seems similar to other pages. Let me know which section should I be changing 

Thank you

**Comment by JessiJess** [comment]
Hi @fritzelemino ,

Yes this is the page. If you refer to the above drawing (separated in 4 parts), you will see that the layout is a little bit different that what we currently have on the website. 

In the second part of the drawing, the picture of inside the boat is after the wording while I would rather have it next to it with the possibility to have maybe more than one. Then, on the drawing, I have also suggested to add a button "More about the yacht' (same as 'contact us').  

Finally, on the 3rd part of the drawing, I would like to add a headline in the middle (just above include/exclude) to add 'cruising package'.

1st and 4th part of the drawing are similar to the website so no need to update anything here.

Does it make sense?

Thanks

**Comment by fritzelemino** [comment]
Yes working on this already @JessiJess

**Comment by JessiJess** [comment]
Hi @fritzelemino , hope everything is well with you. Can I have an update on this issue? I will be opening several issues the next week in order to finalise the website. Thanks.

**Comment by fritzelemino** [comment]
Hi @JessiJess , 

Kindly check this one of this works: 
https://www.dropbox.com/s/suig5u14w04hcp6/the-programs-cruising-experience.jpg?dl=0

**Comment by JessiJess** [comment]
Hi @fritzelemino ,

Yes it is definitely better. Just one comment, instead of the button 'learn more' can we have it changed to 'More about the Yacht'? or it is something that I could modify once this version is implemented?

**Comment by fritzelemino** [comment]
Hi @JessiJess , 

Kindly check this one:
https://invis.io/DEWXF522UGY

**Comment by JessiJess** [comment]
Hi @fritzelemino , can you please resend the link, it says that the project has been archived.

**Comment by fritzelemino** [comment]
Hi @JessiJess , 

Steve might have archive the project to  make room for a new one.

Please check dropbox link here:
https://www.dropbox.com/s/suig5u14w04hcp6/the-programs-cruising-experience.jpg?dl=0

**Comment by JessiJess** [comment]
Thanks @fritzelemino ,

Would you please make a final update so I can upload more than one picture and I have also the option to add a video (if available) in the first and second part of this page where the below arrows are:

<img width="485" alt="Cruising page screenshot" src="https://user-images.githubusercontent.com/59960460/79820481-a94baf80-83cf-11ea-99bb-fdce2fca1214.png">

Maybe to look like something more like below so if I want to add like 3 pictures, it will be displayed in smaller format with the option for the client to click on it:

![image](https://user-images.githubusercontent.com/59960460/79820017-98e70500-83ce-11ea-8612-88a60253d46a.png)

Also, just to note that the last part of the page should not be related to the 'regattas onboard eve' but the 'cruising onboard Eve', which is anyway what we have currently on the website so no change here will be needed. 

Thanks,

**Comment by fritzelemino** [comment]
Hi @JessiJess , 

I think it's better if we make them slider, what do you think? please check

https://www.dropbox.com/s/suig5u14w04hcp6/the-programs-cruising-experience.jpg?dl=0

**Comment by JessiJess** [comment]
Hi @fritzelemino , yes it is indeed better. 

I have a couple of more comments before giving that to iLya.

1) For the first part, do you think it will be possible to have a picture or video fitting the whole size of the screen instead of half? More something similar to this: https://www.clipperroundtheworld.com/about/about-the-race

2) About the the buttons 'Contact us today' and  'more about the yacht', can you change it to look like this (all the buttons should have the same design as this one font, colour and shape):
![Button design](https://user-images.githubusercontent.com/59960460/80556582-5d27ed00-8a17-11ea-9bd2-99fafc9db8fc.jpg)
![Button design - White ](https://user-images.githubusercontent.com/59960460/80557406-2e5f4600-8a1a-11ea-95d4-9707a200e2ea.jpg)

3) Possibility to expand 'Cruising package' similar design with what we will have for the page 'About the yacht', with the 'cruising package' aligned left: 
<img width="1086" alt="Cruising experiences" src="https://user-images.githubusercontent.com/59960460/80556781-0ec71e00-8a18-11ea-9910-7a188e45879a.png">

4) Remove completely the following:
<img width="360" alt="Cruising experiences" src="https://user-images.githubusercontent.com/59960460/80557183-70d45300-8a19-11ea-9207-5acf24948e7a.png">

**Comment by fritzelemino** [comment]
Hi @JessiJess , 

Kindly check this one: 
https://www.dropbox.com/s/suig5u14w04hcp6/the-programs-cruising-experience.jpg?dl=0

**Comment by JessiJess** [comment]
Hi @fritzelemino ,

Thank you for the modification. 

Few comments:

1) For the first part, can we have a picture or video fitting the whole size of the screen, same as what you have done for 'about the yacht'. Therefore, I guess we will only have the title + contact us today there and I will add the text to the second part. See attached a picture that can be ideal as full screen:
![IMG_5580](https://user-images.githubusercontent.com/59960460/80936255-9eebd580-8e13-11ea-849e-5d2cefde4ea9.PNG)

2) For the second part, can we have the bullet point not be that big compared to the font size? Plus instead of the button 'contact us today' can this be 'more about the yacht' 

3) For the third part, instead of having 'includes' and 'excludes' expendables, I was more talking about having 'cruising package' expandable. 

4) For the last part, it should actually be linked to 'Yacht cruising onboard Eve' instead of 'Yacht Regattas onboard Eve'. This error is also noted on the current website.

Please let me know if this is not clear.

Thanks

**Comment by fritzelemino** [comment]
Hi @JessiJess , 

Kindly check this one:
https://www.dropbox.com/s/suig5u14w04hcp6/the-programs-cruising-experience.jpg?dl=0

**Comment by JessiJess** [comment]
Hi @fritzelemino ,

Thanks a lot! The picture seems a little bit darker than the original. Any chance to get the boat part clearer? If this is not possible, I would then rather keep the picture that we currently have. Let me know your thoughts

![airlietrip-whitehaven3b-96](https://user-images.githubusercontent.com/59960460/81141926-700b6600-8fb1-11ea-810e-ae6edd74c823.jpg)

Can we have the title 'Cruising package' same font, size and colour as mentioned to you for issue #51 

Finally, are the pictures that will be present in the second part are going to scroll itself or the customer will have to change to see different pictures?

Thanks

**Comment by fritzelemino** [comment]
Hi @JessiJess , kindly check this:
https://www.dropbox.com/s/suig5u14w04hcp6/the-programs-cruising-experience.jpg?dl=0

The images should scroll automatically. We can also put arrows if you want people to control it.

**Comment by JessiJess** [comment]
Hi @fritzelemino , Happy with the automatic scrolling. 

We are getting there. Final update and ready to deploy. I remember that you have asked me the question already if I would like to have the content to fit the width and actually I would like to change my mind and say yes. 

![InkedCuising design page_LI](https://user-images.githubusercontent.com/59960460/81512837-16b38600-9367-11ea-9f0f-b5125281133e.jpg)

I guess the font size will also get a little bit bigger so the final design will be more like this, with the cruising package title and the '+' and '-' instead of begin read being dark blue as our main menu.

![image](https://user-images.githubusercontent.com/59960460/81512948-fd5f0980-9367-11ea-8309-08e07c2a130d.png)

**Comment by fritzelemino** [comment]
Hi @JessiJess , 

Please check this:https://www.dropbox.com/s/suig5u14w04hcp6/the-programs-cruising-experience.jpg?dl=0

I recommend that the packages stay as is. Doesn't look good when covering the entire width

**Comment by JessiJess** [comment]
Hi @fritzelemino , can the pictures added onto the second part are not physically touching with the picture added onto the title?

**Comment by JessiJess** [comment]
Hi @fritzelemino , can I have an update on this issue?

**Comment by fritzelemino** [comment]
Hi @JessiJess , 

For some reason, I didn't get notifications with these new comments, please check this: https://www.dropbox.com/s/suig5u14w04hcp6/the-programs-cruising-experience.jpg?dl=0

**Comment by JessiJess** [comment]
Hi @fritzelemino , perfect!

@webilhan , please see below the source doc to deploy:
https://www.dropbox.com/sh/nemv5v92ztguth1/AADMJy8QnUW1aubLJxVL7HSea?dl=0&preview=the-programs-cruising-experience.psd

**Comment by webilhan** [comment]
Hi @JessiJess Please kindly check [dev ](https://smooth-falcon.cloudvent.net/cruising.html) site with the new version.

**Comment by JessiJess** [comment]
Thanks @webilhan , few comments:
- Can the title be aligned left with the same margin as the text below?
- You are missing the 'i' for Cruising package title but I guess I can update that from admin view

Finally, would I be able as admin to add another subsection similar to 'cruising package'. I was thinking about adding something like 'what to expect' just before cruising package section.

**Comment by JessiJess** [comment]
@webilhan , do you have an update on the above?

**Comment by webilhan** [comment]
@JessiJess Updated as per the last comment, see on [dev](https://smooth-falcon.cloudvent.net/cruising.html) site. You can easily add/remove subsections in admin. Left sidebar, "Sections" block

**Comment by JessiJess** [comment]
@webilhan thanks. Looks good. Do the pictures on the second section automatically switched right/left or there will be some kind of arrows for the users to change from one pic to another?

**Comment by webilhan** [comment]
@JessiJess Added Gallery section for each second section, you can see example how manage image in #54.

**Comment by JessiJess** [comment]
@webilhan , perfect then you can deploy. Just ensure that the titles have the same font that website menu and instead of black for the colour of the titles in section please change to dark blue, same comment for 'more about the yacht'.

![image](https://user-images.githubusercontent.com/59960460/86546081-3be30000-bf76-11ea-93bb-f76deb383103.png)

**Comment by webilhan** [comment]
Color changed, font for title is the same.

Please check on [dev site](https://smooth-falcon.cloudvent.net/cruising.html) and confirm that we can deploy new versions for (#44, #51 and #54), becasue they should be deployed together?
