### ISSUE TITLE
Tabs to be reorganised

### ISSUE THREAD

**Issue by JessiJess** [gs-gs/swanningaround#45]
Hi @webilhan , I will need your support in reorganising the tab in our website in the left side. Below is currently what we have:

![image](https://user-images.githubusercontent.com/59960460/79712751-10555f80-830f-11ea-9e0e-123c28c17cb2.png)

And below is I would like them to be reorganised:

- HOME
- EXPLORE
- YOUR EXPERIENCES
         => Cruising
                      >> Watersport Charters
         => Passages
         => Races & Regattas
- THE CREW
- EVE TRACKER
- SAFETY 
- CONTACT US

I am happy to make a draft if the above instructions are not clear enough.

Thanks

**Comment by JessiJess** [comment]
Just to note that the content of 'Watersport charters' page is being currently finalised and should be available within the next couple of days.

**Comment by webilhan** [comment]
@JessiJess "YOUR EXPERIENCES" will be a collapsible menu, so by clicking on it, submenu will be toggle?

**Comment by JessiJess** [comment]
@webilhan , yes I do not want to create a static page 'experiences' just as you said when you click on it  or just actually pass with the mouse, all the other static pages are visible. 
To clarify further:
- Watersport page will be a submenu of cruising however we should be able to click on cruising and see the content and also watersport and see the content. 
- Races and Regattas will merge and become one page only

**Comment by webilhan** [comment]
@JessiJess @onthebreeze Menu reorganised and deployed on DEV site. https://smooth-falcon.cloudvent.net/about-the-yacht.html 
@JessiJess Please note that you can easily manage menu items from admin, see:
1. http://prntscr.com/s6c02y
2. http://prntscr.com/s6c0d7

**Comment by JessiJess** [comment]
@webilhan, thanks! Just one comment, is it possible for the 'Watersport Charters' tab to be a sub tab of cruising instead of being a sub tab of 'our experiences' ? If I can do it myself from admin all good, i will modify it after online.

**Comment by webilhan** [comment]
@JessiJess Deployed to Live site. **Watersport Charters** tab was added as a sub tab. Please note that for now it is an empty page, so would be good to fill it with content.

**Comment by JessiJess** [comment]
Hi @webilhan ,

Thank you for deploying the tab. I have added now the content to Watersport Charters. For some reason, I have not the option to delete some unnecessary content and space, please see screenshot below:

![Watersport charter](https://user-images.githubusercontent.com/59960460/81024585-2dfdf980-8eb7-11ea-8c21-9190541d8aaa.jpg)

Also, I would like to let you know that we are reviewing the page design with Fritz so once this is finalised, I will be reaching out to you to deploy.

Thank you again for your prompt action

**Comment by JessiJess** [comment]
Hi @webilhan , do you have an update on the issue mentioned above?

**Comment by webilhan** [comment]
@JessiJess  Removed unnecessary content and spaces. Please check on live site.
When you will have updated design just let me know.
