### ISSUE TITLE
Linked Facebook & TripAdvisor review to the website

### ISSUE THREAD

**Issue by JessiJess** [gs-gs/swanningaround#46]
Hi, 

I would like to have future clients visiting the website to be able to see our reviews. If you look at the following website (www.pilgrimsailing.com.au), you have the reviews from Facebook and TripAdvisor that scrolled right to left and you can click on each review and it brings you to the actual Facebook and TripAdvisor pages where the review is.  

Can we have a similar activity in each static pages (Cruising/Passages/Races&Regattas) at the bottom of the page? 

Here is our page on TripAdvisor: https://www.tripadvisor.com.au/Attraction_Review-g255060-d13001989-Reviews-Swanning_Around-Sydney_New_South_Wales.html
And on Facebook: https://www.facebook.com/pg/swanningaroundcharters/reviews/?ref=page_internal

Thanks

**Comment by onthebreeze** [comment]
@webilhan - do you need a design for this from @fritzelemino - or can you juts have a got for @JessiJess review?

**Comment by webilhan** [comment]
@onthebreeze @JessiJess I can add a section where you can add these reviews and show them on frontend. Should reviews be the same on all static pages?

**Comment by JessiJess** [comment]
@webilhan, 
What do you mean by adding the review, so this will not be automatic? I rather have something that automatically add the reviews on the website to avoid to add each new review. If those reviews can be added that way then yes it will be the same on Cruising, passage and races&regattas as unfortunately the reviews posted on FB or TripAdvisor does not have a way to classify them.  

@onthebreeze What will be your preference? That I classify, copy and paste the reviews into our website or they are added automatically, the same way as pilgrim website is design?

**Comment by webilhan** [comment]
@JessiJess @onthebreeze They use https://repuso.com/ service. We can try to use API FB and TripAdvisor, but that's needs to be investigated.
With automatic way, there is a question: what if somebody posted review which you don't want to show on the site?

**Comment by JessiJess** [comment]
@webilhan , is there an option maybe where you can select the reviews to add on the website without me having to copy/past the whole thing?

**Comment by webilhan** [comment]
@JessiJess Do you mean option on repuso.com service or in admin?
1. If you mean in service, I don't know, never worked with it.
2. In admin we don't have such option and I don't think that this is reasonable to create it, because it will take a lot of time.

**Comment by JessiJess** [comment]
@webilhan , no worries, let's try to keep it simple then. I guess the best/easiest option here is for me to add those reviews into the website. Will the customer be able to click on the review and it will take him to Facebook or TripAdvisor? The best option will be to have the reviews pertaining to cruising on the cruising page, passage reviews on the passage page and so on. I will be managing that at admin level.

**Comment by JessiJess** [comment]
@webilhan  , do you have an update on the above?

**Comment by JessiJess** [comment]
@webilhan just letting you know that we will not be using TripAdvisor at all but instead build a strong clientele engagement in Facebook so all our reviews will come from there. Thanks.

**Comment by webilhan** [comment]
@JessiJess @onthebreeze 
I've deployed reviews functionality on DEV site, See for example [Cruising page](https://smooth-falcon.cloudvent.net/cruising.html).
You can edit reviews at admin _Expore->Data->Reviews_ (https://prnt.sc/tt4vuo).
Depending on the "Review Type" field review will be shown on the related page.

Let me know if you need something to change.

**Comment by webilhan** [comment]
@JessiJess Deployed on live site, so now you can manage it from admin.
