### ISSUE TITLE
Coronavirus update page

### ISSUE THREAD

**Issue by JessiJess** [gs-gs/swanningaround#48]
Hi @webilhan , I am currently drafting a quick content to update our customers on how the whole trip has been impacted by COVID and what next. For that I will need you to add on the Home page (where the video is), right between 'GLOBAL SAILING ADVENTURES' AND 'EXPLORE OUR WORLD' , the following: 'Coronavirus (COVID-19) update'. Same design as 'Explore our world'. When the customer will click on it a page will pop up with the updates on, something like that:

![Coronavirus Home page example](https://user-images.githubusercontent.com/59960460/80053162-9e278980-855f-11ea-820e-06d68ce44c77.png)

With a policy and background blue colour similar to that the one below (will create another issue to make the below change to our homepage)

![3_ SwanningAround - Website - Corrections Homepage Menu 01](https://user-images.githubusercontent.com/59960460/80053869-4722b400-8561-11ea-8294-b2042d230d42.jpg)

**Comment by webilhan** [comment]
@JessiJess @onthebreeze I've added button and popup on the homepage. Please check on DEV site: https://smooth-falcon.cloudvent.net/
Content and visibility could be managed at the admin panel:
1. http://prntscr.com/s6c02y
2. http://prntscr.com/s6c23i
3. http://prntscr.com/s6c2wm

**Comment by JessiJess** [comment]
@webilhan , perfect! Please deploy and will add the content at the admin panel.

**Comment by webilhan** [comment]
@JessiJess Deployed. To show it please add content and select checkbox **Enabled**

**Comment by JessiJess** [comment]
Thanks @webilhan . Content added.
