### ISSUE TITLE
Tab Design Correction (Font - Police - Background)

### ISSUE THREAD

**Issue by JessiJess** [gs-gs/swanningaround#49]
Hi @webilhan , Can you please update the homepage from the following:

<img width="1074" alt="Homepage - Current" src="https://user-images.githubusercontent.com/59960460/80054477-b8169b80-8562-11ea-93bb-aedec0ee828b.png">

To:

![3_ SwanningAround - Website - Corrections Homepage Menu 01](https://user-images.githubusercontent.com/59960460/80054294-2c047400-8562-11ea-86da-cdf04b98a1dd.jpg)

Of course, the issue #45 will need to be completed first. 

I have also attached the FONT that was shared by the designer few months ago to implement into our website. 

[TITLES FONT-20200423T031458Z-001.zip](https://github.com/gs-gs/swanningaround/files/4520053/TITLES.FONT-20200423T031458Z-001.zip)

Please let me know if any questions.

**Comment by webilhan** [comment]
@JessiJess @onthebreeze Updated main menu for homepage and updated fonts.
Please check on DEV site: https://smooth-falcon.cloudvent.net/

**Comment by JessiJess** [comment]
@webilhan , very nice thanks! Can we have the updated main menu design not only from homepage but also from any other pages - keeping the same design everywhere on the website?

**Comment by webilhan** [comment]
@JessiJess Updated main menu design for all pages. Deployed on Live site.

**Comment by JessiJess** [comment]
Hi @webilhan , thank you for updating the main menu design. Can you confirm that you will also apply the same font/size to the entire website based on the zip folder that I have shared with you?

[FONT-20200504T034921Z-001.zip](https://github.com/gs-gs/swanningaround/files/4578603/FONT-20200504T034921Z-001.zip)

**Comment by JessiJess** [comment]
Hi @webilhan , can you please just confirm and I will close this issue. Thanks

**Comment by webilhan** [comment]
@JessiJess Could you explain where which font I should use or provide PSD with right fonts.

**Comment by JessiJess** [comment]
Hi @webilhan , sorry, is the document attached here not sufficient enough to find the correct fonts?
[TITLES.FONT-20200423T031458Z-001.zip](https://github.com/gs-gs/swanningaround/files/4626036/TITLES.FONT-20200423T031458Z-001.zip)

You have 3 different:
- Proto Grotesk ExtraLight
- Proto Grotesk Light
- Proto Grotesk regular

I would like to have those 3 fonts setup and have the capacity as an admin to change the fonts. Is it possible?

**Comment by JessiJess** [comment]
Hi @webilhan , just checking if you have an update on this issue?

**Comment by webilhan** [comment]
@JessiJess In attached zip I only see font source files, but I need to know where which font I should use. It is not possible to make option in the admin for choosing fonts, it could be done only for the part fo content that you can edit.
Would be good to have some screenshot with notations where do you want to change the font.
