### ISSUE TITLE
Static Page redesign - 'About the yacht'

### ISSUE THREAD

**Issue by JessiJess** [gs-gs/swanningaround#51]
Hi @fritzelemino , 

I would like to redesign the static page 'about the yacht' https://swanningaround.com/about-the-yacht.html and have it similar to this: https://www.clipperroundtheworld.com/race/fleet

I have made a quick draft below on how it will look like for our website:
![About the yacht - draft](https://user-images.githubusercontent.com/59960460/80331115-86ffd900-888a-11ea-9019-86a639419890.jpg)

When we extend the Exterior and interior, I will have some content and few pictures display in nice way. The content of the specification will remain the same as we currently have.

Please let me know if you have any questions or comments.

Thanks,

**Comment by fritzelemino** [comment]
Hi @JessiJess , 

Kindly check this one: https://www.dropbox.com/s/7uhwz2d0ib5j16r/About-Yatch.jpg?dl=0

Do you want to use the whole width?

**Comment by JessiJess** [comment]
Hi @fritzelemino , not the whole width, I will say half the size for the information and the other half for pictures. So if we take the example of the website mentioned above when you expand 'interior', we will have some info on our right and below the tile 'interior' I would have the option to add few pictures.   
<img width="1071" alt="About the Yacht - sample" src="https://user-images.githubusercontent.com/59960460/80554128-76c53680-8a0f-11ea-9e1e-616460d5b445.png">

Regarding with your proposition, I guess we can keep history how it is with the info and the picture / video right below the text. Can you add on the top part the picture of the whole boat instead of the couch just to see how it looks? I will be keen in having something really similar to the below screenshot, with the picture taking the whole first part of the screen:

<img width="1074" alt="About the yacht top part" src="https://user-images.githubusercontent.com/59960460/80554407-61044100-8a10-11ea-8b88-70b431259be1.png">

Also, just to note, the last part 'keen to do a regatta (...), should not be present on this static page.

Thanks

**Comment by fritzelemino** [comment]
Hi @JessiJess , 

Kindly check this:https://www.dropbox.com/s/7uhwz2d0ib5j16r/About-Yatch.jpg?dl=0

Few things:
+ The current font **Alliance no. 1** only has a light version. This was the font used by the other designer and Steve also instructed me to use this. But this font doesn't fit very well with light Background, It's unreadable. Should we change this? I used roboto bold on the above mock up.
+ I only use the image I have but it's very small. Do we have a higher resolution version of this image?

Let me know your thoughts

Thank you
Regards
Fritz

**Comment by JessiJess** [comment]
Hi @fritzelemino ,
Looks way better! We can remove the 'contact us today' just below the main title. 

- About the font, see attached what has been proposed by the designer last year and let me know if you think this font will be more appropriate. 
[FONT-20200504T034921Z-001.zip](https://github.com/gs-gs/swanningaround/files/4572723/FONT-20200504T034921Z-001.zip)


- Please see attached the original photo. 
![1708210150 Race Week Day 2_5410x3607_1941445](https://user-images.githubusercontent.com/59960460/80935347-85488f00-8e0f-11ea-97a9-ec52581f9b92.jpg)


Thank you for your great job :)

**Comment by fritzelemino** [comment]
Hi @JessiJess , 

Kindly check this one:
https://www.dropbox.com/s/7uhwz2d0ib5j16r/About-Yatch.jpg?dl=0

**Comment by JessiJess** [comment]
Hi @fritzelemino , Perfect! Can you just change the font and size to the title 'Our history' / Interior / Exterior / Specification to match our main menu and a font size colour dark blue?

![3_ SwanningAround - Website - Corrections Homepage Menu 01](https://user-images.githubusercontent.com/59960460/81139912-db056e80-8faa-11ea-9f39-e6f1fa7e449f.jpg)

![Button design - White ](https://user-images.githubusercontent.com/59960460/81140022-43ece680-8fab-11ea-9963-3bf4595f56d0.jpg)

Once you send me another version I will let Ilya knows.

Cheers

**Comment by fritzelemino** [comment]
Hi @JessiJess , 

Kindly check these:
https://www.dropbox.com/s/7uhwz2d0ib5j16r/About-Yatch.jpg?dl=0

Let m

**Comment by JessiJess** [comment]
Hi @fritzelemino , it looks like the titles' colour are still black? Is it possible to change the colour to dark blue as below. Is it the same font as below that you use?
![Button design - White ](https://user-images.githubusercontent.com/59960460/81513236-3c8e5a00-936a-11ea-8233-9f49a5dd9b4a.jpg)

Also, the modification that I have mentioned in issue #44 will be applicable to this page too (fit the whole width). 

Thanks

**Comment by fritzelemino** [comment]
@JessiJess , 

Kindly check this:
https://www.dropbox.com/s/7uhwz2d0ib5j16r/About-Yatch.jpg?dl=0

The current font is already the one you have above. The current font is also the one you sent me  Proto Grotesk. This is better fit than the one on the button right now.

**Comment by JessiJess** [comment]
@fritzelemino , perfect.

@webilhan , can you please deploy the above updated design on 'About the Yacht' page? Also, please ensure that we can the pictures that will be added onto different part (History, interior and exterior) scroll automatically. Thanks

**Comment by webilhan** [comment]
@fritzelemino Could you share the source of design with me?

**Comment by fritzelemino** [comment]
Please check PSDs here: https://www.dropbox.com/sh/nemv5v92ztguth1/AADMJy8QnUW1aubLJxVL7HSea?dl=0

**Comment by JessiJess** [comment]
Hi @webilhan , just a comment about the PSDs shared, please ensure the the title 'about the Yacht' is aligned left to be at the same margin size as 'Our history' . Thanks

**Comment by JessiJess** [comment]
Hi @webilhan , do you have an update on this issue?

**Comment by webilhan** [comment]
Hi @JessiJess Please kindly check [dev](https://smooth-falcon.cloudvent.net/about-the-yacht.html) site with the new version.

**Comment by JessiJess** [comment]
Great, just few comments:
- Can we aligned 'about the yacht' left same as 'Our history' 
Can you please ensure that I will be able to add several pictures in each sub section (interior and exterior) with automatic scrolling?
Also, I will not add the picture in the section our history but I am sure I will be able to delete this as admin.

**Comment by JessiJess** [comment]
Hi @webilhan , do you have an update?

**Comment by webilhan** [comment]
> Can you please ensure that I will be able to add several pictures in each sub section (interior and exterior) with automatic scrolling?
What do you mean by automatic scrolling? Would be good to have these pictures. 
Where do you want to place pictures? Would be easier to place before or after text, not in the middle

**Comment by JessiJess** [comment]
@webilhan I meant by that, in the section interior and exterior, make the pictures scroll left (i.e. from right to left), after the text. Similar to this example https://www.clipperroundtheworld.com/race/fleet, when you go to the 15 pictures at the end, you will see that the pictures automatically switched and users have also the option by clicking on the arrow to make the switch. 
Does that make sense?

**Comment by webilhan** [comment]
@JessiJess Added Gallery section for each subsections, you can see example how manage image in #54.

**Comment by JessiJess** [comment]
All good then, can you show me the update dev site with the new version? Please also ensure that the titles are the same font that we have on our menu in the website. Thanks

**Comment by webilhan** [comment]
All the titles have the same font.
Please check on [dev site](https://smooth-falcon.cloudvent.net/about-the-yacht.html) and confirm that we can deploy new version?

**Comment by JessiJess** [comment]
Yes, please deploy
