### ISSUE TITLE
Contact us Today

### ISSUE THREAD

**Issue by JessiJess** [gs-gs/swanningaround#52]
Hi @webilhan , can you please update the contact page to have it looks like that:
![5_ SwanningAround - Website - correction contact page](https://user-images.githubusercontent.com/59960460/80332302-d1cf2000-888d-11ea-92c8-af7d7957d425.jpg)

I guess you have the picture that had a better quality too however if not I will do it when this version is online.

The font & police will need to be updated too so it is the same in all pages and not just the tab menu and contact us. 

Thanks.

**Comment by webilhan** [comment]
@JessiJess Do you have original source file (PSD or any other where the design was created). For me would be much easier to detect fonts/colors/sizes, if I get source file instead JPG.

**Comment by webilhan** [comment]
@JessiJess I've deployed draft version on test site, please check - https://smooth-falcon.cloudvent.net/contact-us.html Fonts could be not fully right. Let me know you need to change  it?

**Comment by JessiJess** [comment]
Hi @webilhan , perfect! Please deploy. With regards to the PSD, I have asked the designer to provide and shall forward it to you once available.

**Comment by JessiJess** [comment]
Hi @webilhan , can you please have an update on the above issue?

**Comment by webilhan** [comment]
@JessiJess Deployed on Prod.
