### ISSUE TITLE
Favicon correction

### ISSUE THREAD

**Issue by JessiJess** [gs-gs/swanningaround#53]
Hi @webilhan ,

The current Favicon on the website is incorrect. 
<img width="1128" alt="Favicon" src="https://user-images.githubusercontent.com/59960460/81029792-a66db600-8ec9-11ea-8591-b25cca9c1a55.png">

Please kindly update based on below zip folder.
[FAVICON.zip](https://github.com/gs-gs/swanningaround/files/4578642/FAVICON.zip)

Many thanks

**Comment by JessiJess** [comment]
Hi @webilhan , any update on the above issue?

**Comment by webilhan** [comment]
@JessiJess I've deployed new favicon on test server. Please clear browser cache and check on https://smooth-falcon.cloudvent.net/

**Comment by JessiJess** [comment]
Hi @webilhan , all good thanks.

**Comment by webilhan** [comment]
@JessiJess Deploy on Live site.
