### ISSUE TITLE
Static page redesign - Passages

### ISSUE THREAD

**Issue by JessiJess** [gs-gs/swanningaround#54]
Hi @fritzelemino , please find below a draft of how I would like the static page about 'Passages' be redesigned:

![Passage redesign](https://user-images.githubusercontent.com/59960460/81534114-d1b14300-93aa-11ea-85aa-4821db7d7f28.jpg)

For the picture on the title, you can use the best of the 2 choices below:
![Eve-Sydney-Noumea_RaceStart](https://user-images.githubusercontent.com/59960460/81534269-1c32bf80-93ab-11ea-8a90-be3940c59f91.jpeg)

![ocean shot at start](https://user-images.githubusercontent.com/59960460/81534396-5308d580-93ab-11ea-9646-2deb99c923a5.jpg)

**Comment by JessiJess** [comment]
@fritzelemino , do you have an update on this issue?

**Comment by fritzelemino** [comment]
Hi @JessiJess , 

I'm working on this already

**Comment by JessiJess** [comment]
@fritzelemino , just checking if you have any update on the advancement of this page?

**Comment by fritzelemino** [comment]
Hi @JessiJess , 

Please check: https://www.dropbox.com/s/wbyv5zs5yfw0ags/the-passages.jpg?dl=0

**Comment by JessiJess** [comment]
Hi @fritzelemino , perfect. 

Please kindly share the PSD file to @webilhan so he can deploy it.

**Comment by webilhan** [comment]
@JessiJess Applied new version of design for Passages page. Please kindly check on [dev](https://smooth-falcon.cloudvent.net/ocean-passages.html) site. See also gallery images, you can manage it from admin. See [screen](https://prnt.sc/tccqpz) for the section "More about the yacht" and for [subsections](https://prnt.sc/tccr3x)

**Comment by JessiJess** [comment]
Hi @webilhan looks really good thanks! 

Just couple of comments: 
1) Can you confirm that the title font are the same that we have in our drop down list menu on the website? 

2) Can you just change the colour on the 'More about the yacht' when you click on it from black to the same dark blue that we have in our drop down list menu on the website? 

3) I am not too sure if I will add any pictures on the sections 'What to expect', so just want to make sure that if no picture is displayed, this will not show as an empty space online.

**Comment by webilhan** [comment]
1. Yes it is the same Here is menu font - https://prnt.sc/teb9t8 and here is title font - https://prnt.sc/teba9c
2. Changed color to #021221 like background in dropdown menu
3. Yes, if there are no images, nothing will be shown. I've remove images from that section.

Please check on [dev site](https://smooth-falcon.cloudvent.net/ocean-passages.html) and confirm that we can deploy new version?

**Comment by JessiJess** [comment]
Yes please deploy. Have you started working already on #55 as it will be nice to have this deployed with the others. Please note that I have started marketing and therefore I am expecting potential clients visiting our website so it will be appreciated if those issues can be closed as soon as possible so I can make my updates online too. Thanks
