### ISSUE TITLE
Static Page redesign - Ocean Races & Regattas

### ISSUE THREAD

**Issue by JessiJess** [gs-gs/swanningaround#55]
Hi @fritzelemino , please find below a draft of how I would like the static page about 'Races & Regattas' be redesigned:

![80262629_710590639741452_7466215324719534238_n](https://user-images.githubusercontent.com/59960460/86524870-47292380-bec3-11ea-919e-2392e258e428.jpg)

For the first section, the picture on the title, you can use the below picture:
![1708210156 Race Week Day 2_5158x3439_1941490](https://user-images.githubusercontent.com/59960460/86525256-48a91a80-bec8-11ea-936a-6fa8179fed80.jpg)

With regards to the section: The regatta,can we have the below video without sound added below the text?
https://rosielord.wetransfer.com/downloads/31b012b7d6d8776a7b2a50f687fc712520200703125609/c9ab1b

**Comment by fritzelemino** [comment]
Hi @JessiJess , 

Please check:
https://www.dropbox.com/s/wj5cosp5433iwxe/Regattas-and-Ocean-Races.jpg?dl=0

Thank you

Regards,

**Comment by JessiJess** [comment]
Hi @fritzelemino , looks good. The last title is 'Racing package' but I will be able to update that.
Can you please share the PSD file for iLya?

@webilhan , please check out the new design to implement to website. 
Would you be able also to add the below video without sound to the section 'The regatta' below the text? https://rosielord.wetransfer.com/downloads/31b012b7d6d8776a7b2a50f687fc712520200703125609/c9ab1b

**Comment by fritzelemino** [comment]
Please check PSD here: https://www.dropbox.com/s/jhb8uph0tylkt4i/Regattas%20and%20Ocean%20Races.psd?dl=0

**Comment by webilhan** [comment]
Hi @JessiJess 
I've applied new design and deployed on [dev](https://smooth-falcon.cloudvent.net/ocean-races.html) site. Please check and let me know if everything is ok?

**Comment by JessiJess** [comment]
Hi @webilhan , perfect, you can deploy thanks.

**Comment by JessiJess** [comment]
Hi @webilhan any update?

**Comment by webilhan** [comment]
@JessiJess Deployed to live site. Please check.
