### ISSUE TITLE
Static page redesign - Watersport Charters

### ISSUE THREAD

**Issue by JessiJess** [gs-gs/swanningaround#56]
Hi @fritzelemino, please find below a draft of how I would like the static page about 'Watersport Charters' be redesigned. It will be slightly different that the other pages as this one is a subsection of the cruising page. 

![image](https://user-images.githubusercontent.com/59960460/86547339-08a36f80-bf7c-11ea-8063-9213ef768c0f.png)

With regards to the pictures, here is few that you can use, I guess the first one will look the best to add at the top:
![PB091695](https://user-images.githubusercontent.com/59960460/86547469-79e32280-bf7c-11ea-9d46-6a8f3d26576c.JPG)
![PB081682](https://user-images.githubusercontent.com/59960460/86547502-967f5a80-bf7c-11ea-984d-4f5653185f2d.JPG)
![PB081654](https://user-images.githubusercontent.com/59960460/86547946-f6c2cc00-bf7d-11ea-815d-2d4ec90dd16f.JPG)
![watersport 2](https://user-images.githubusercontent.com/59960460/86547573-c9295300-bf7c-11ea-8365-d97c8c3dd302.jpg)

**Comment by fritzelemino** [comment]
Hi @JessiJess , please check this one:

I can't red the image enough to identify the text on the package section. 

https://www.dropbox.com/s/35wuqu05a6udryt/Watersport-Charters.jpg?dl=0

**Comment by JessiJess** [comment]
Hi @fritzelemino , thank you for your prompt response. I am not sure what text you cannot read. Anyway, I am happy with your proposition, just you can remove the 'more about the yacht' in the second section, it will only appear in the section: 'What to expect'. Can you update and share with @webilhan the PSD file?

**Comment by fritzelemino** [comment]
Please check PSD here:

@webilhan https://www.dropbox.com/s/kiio0u0vr5wust1/Watersport%20Charters.psd?dl=0

**Comment by JessiJess** [comment]
Hi @webilhan here we go. Please just ensure that the last part is linked with the cruising charter and not the regattas. Thanks to you both.

**Comment by webilhan** [comment]
@JessiJess Done, deployed on [live site](https://swanningaround.com/watersport-charters.html). Please check

**Comment by JessiJess** [comment]
@webilhan , the design is a bit different that PSD file. Can you update is to ensure it is similar to the PS (button 'more about the yacht' is missing on the section 'what to expect' and the section 'what to expect' to be open and not expendable). Thanks

**Comment by webilhan** [comment]
@JessiJess Updated. Deployed to [live site.](https://swanningaround.com/watersport-charters.html)
