### ISSUE TITLE
Explore page - User Friendly

### ISSUE THREAD

**Issue by JessiJess** [gs-gs/swanningaround#57]
Hi @webilhan , we have discussed with Steve yesterday about our explore page with the map and we found it both quite hard to navigate from. Below is a suggestion of how we think it will make the page more users friendly:

![Swanning_Around_Tab views](https://user-images.githubusercontent.com/59960460/87392363-bd2e3880-c5ef-11ea-884c-54fbf3e14bcf.png)

Thank you.

**Comment by webilhan** [comment]
@JessiJess Should it be just transparent text without borders?

**Comment by webilhan** [comment]
One more question should it be only for map view?

**Comment by JessiJess** [comment]
@webilhan , maybe we can have some sort of the same design that we already have as below when the colour changed when the mouse is on the button. 

<img width="677" alt="Untitled" src="https://user-images.githubusercontent.com/59960460/87612089-f7611c80-c74c-11ea-9c16-d9f824be7386.png">

I think it should also be on the calendar view so user can go back to map view if they want. It is just that the option that we have right now to switch from map to calendar is not enough obvious.

**Comment by JessiJess** [comment]
Hi @fritzelemino , can you please have a look to this issue and propose a design for it that is consistent with our current website?
Ilya advised me that the above suggestion did not look good. Thank you for your proposition.

**Comment by fritzelemino** [comment]
Hi @JessiJess,

I recommend this style and when user hovers the menu we can show a tool tip of the description:
https://www.dropbox.com/sh/vu9os7o4idt6eqt/AADJVUOvM_Aeb3Km1BTwX9hwa?dl=0

Let me know your thoughts.

**Comment by JessiJess** [comment]
Hi @fritzelemino , thank you! I like the idea of the tab however not a big fan of the design, would you just make the tab fits the width screen and having the color of the tab the same dark blue of our menu?

**Comment by fritzelemino** [comment]
Hi @JessiJess 

Please check these: https://www.dropbox.com/sh/vu9os7o4idt6eqt/AADJVUOvM_Aeb3Km1BTwX9hwa?dl=0

Let me know your thoughts

**Comment by JessiJess** [comment]
Hi @fritzelemino , sorry I am not a big fan of the design, the writing is not proportional to the tab it makes it weird. Do you have any other suggestions?

**Comment by fritzelemino** [comment]
HI @JessiJess , 

Please check if this  works so I can implement on other screen:
https://www.dropbox.com/s/7d33vxh4od80qn2/SA-Discovery-Page-Updated.jpg?dl=0

**Comment by JessiJess** [comment]
Hi @fritzelemino , way better. I like it like that. Please implement to other screen and provide PSD file to Ilya.
Thank you!

**Comment by fritzelemino** [comment]
@webilhan @JessiJess , 

Please check JPGs and PSDs here:
https://www.dropbox.com/sh/vu9os7o4idt6eqt/AADJVUOvM_Aeb3Km1BTwX9hwa?dl=0

Thank you

**Comment by webilhan** [comment]
@JessiJess Implemented design from the last PSD. Please check on [DEV](https://smooth-falcon.cloudvent.net/explore) site. 
Let me know if it can be deployed on Live site.

**Comment by JessiJess** [comment]
@webilhan very nice, please deploy.

**Comment by webilhan** [comment]
@JessiJess Deployed on Live site.
