### ISSUE TITLE
Events Cancellation 

### ISSUE THREAD

**Issue by JessiJess** [gs-gs/swanningaround#58]
Hi @webilhan , I would like to show that some regattas have been canceled however I do not want to remove them from user visibility. Do you need Fritz to have a look at it first?

I was thinking about something similar to this:

![image](https://user-images.githubusercontent.com/59960460/89133719-89e12880-d561-11ea-9c0e-4abd7cfe95b3.png)

![OIP](https://user-images.githubusercontent.com/59960460/89133776-34f1e200-d562-11ea-9fd6-6ec4ff1c54a5.jpg)

We will not be doing those below:
![image](https://user-images.githubusercontent.com/59960460/89133671-2656fb00-d561-11ea-8cfc-a31607beab4d.png)

**Comment by webilhan** [comment]
For each experience added new attribute [is cancelled](http://prntscr.com/tty75k). If it is set true label **CANCELLED** shows on 3 pages:
- Experience description static page, like [REGATTAS & OCEAN RACES](https://smooth-falcon.cloudvent.net/ocean-races.html) 
- Explore page when experience selected, see [screenshot](http://prntscr.com/tty8oz) 
- And experience detail page, for example [Hamilton Island Race Week](https://smooth-falcon.cloudvent.net/regattas/hamilton-island-race-week.html)

@JessiJess Please check on DEV site and let me know you want to change anything.

**Comment by JessiJess** [comment]
@webilhan , perfect, please deploy to live. Thanks

**Comment by webilhan** [comment]
@JessiJess Deployed on Live site.
