### ISSUE TITLE
Metadata - Meta Description & title fields to be created

### ISSUE THREAD

**Issue by JessiJess** [gs-gs/swanningaround#59]
Hi @webilhan , I have discussed with my friend, and apparently the Keywords field is no longer used by Google for SEO. However, I will need to add metadata for each passage, race and cruise that we will be doing in order to be visible in google. We do only have those fields (title and description) for our standalone pages. Can you please add those fields on the other pages?

Cheers

**Comment by webilhan** [comment]
@JessiJess Added SEO section with title, description and keyword fields for all experience types. If it is filled we will show it, if no show title and description from experience itself. See [screenshot 1](https://prnt.sc/u8ct48) and [screenshot 2](https://prnt.sc/u8cu6a) 
Deployed on Live site.
